config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  post "events/:id/add_existing_users" => "events#add_existing_users", as: :add_existing_users
  post "events/:id/add_new_users" => "events#add_new_users", as: :add_new_users
  patch "events/:id/add_participation" => "events#add_participation", as: :add_participation
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/' => 'home#index', as: :home

  resources :users
  resources :events

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :events, through: :event_users
  has_many :event_users

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update).push(:password_confirmation, :current_password, :email, :fname, :lname, :address, :phone, :likes, :dislikes, :add_info)
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super do |user|
      UserMailer.welcome_email(user).deliver_later
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private
  def user_params
    params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :address, :phone, :username, :likes, :dislikes, :add_info)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def index
    @users = User.all
    @title = 'All users'
  end

  def show
    
    # get user and associated events
    #
    @user = User.find(params[:id])
    events = @user.events
    #
    # separate user's events into pending and past
    #
    @pending_events = []
    @past_events = []
    @title = @user.email

    events.each do |event|
      if event.date >= Time.now
        @pending_events << event
      else
        @past_events << event
      end
    end

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_other_profile.html.erb
<body class="content-wrapper">

	<%= render :partial => "/layouts/navbar" %>
	
	<div class="profile-large-box">
		<% if @user.fname == nil || @user.lname == nil %>
			<h1><center><%= @user.email %></center></h1>
		<% else %>
			<h1><center><%= "#{@user.fname} #{@user.lname}" %></center></h1>
		<% end %>

		<h4 class="red-text">Address</h4>
		<% if @user.address == "" || @user.address == nil %>
			<h4> none </h4>
		<% else %>
			<h4><%= @user.address %></h4>
		<% end %>
		
		<h4 class="red-text">Phone</h4>
		<% if @user.phone == "" || @user.phone == nil %>
			<h4> none </h4>
		<% else %>
			<h4><%= @user.phone %></h4>
		<% end %>
		
		<h4 class="red-text">Email</h4>
		<% if @user.email == "" || @user.email == nil %>
			<h4> none </h4>
		<% else %>
			<h4><%= @user.email %></h4>
		<% end %>

		<h4 class="red-text">Likes</h4>
		<% if @user.likes == "" || @user.likes == nil %>
			<h4> none </h4>
		<% else %>
			<h4><%= @user.likes %></h4>
		<% end %>
		
		<h4 class="red-text">Dislikes</h4>
		<% if @user.dislikes == "" || @user.dislikes == nil %>
			<h4> none </h4>
		<% else %>
			<h4><%= @user.dislikes %></h4>
		<% end %>
		
		<h4 class="red-text">Additional Info</h4>
		<% if @user.add_info == "" ||  @user.add_info == nil %>
			<h4> none </h4>
		<% else %>
			<h4><%= @user.add_info %></h4>
		<% end %>

	</div>

	<div class="row">
		<div class="column-wrapper center-block">
			<div class="col-md-6 profile-small-box-1">
				<h3>Upcoming events:</h3>
				<% @pending_events.each do |event| %>
				<p>
					<%= link_to event.name, event_path(event.id) %>
				</p>
				<% end %>
			</div>

			<div class="col-md-6 profile-small-box-2">
				<h3>Past events:</h3>
				<% @past_events.each do |event| %>
				<p>
					<%= link_to event.name, event_path(event.id) %>
				</p>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/users/_own_profile.html.erb
<body class="content-wrapper">

	<%= render :partial => "/layouts/navbar" %>

	<div class="row profile-row">

		<div class="col-md-10">
			<div class="profile-large-box">
				<% if @user.fname == nil || @user.lname == nil %>
				<h2><%= "Welcome, #{@user.email}!" %></h2>
				<% else %>
				<h2><%= "Welcome, #{@user.fname} #{@user.lname}!" %></h2>
				<% end %>

				<h4 class="red-text">Address</h4>
				<% if @user.address == "" || @user.address == nil %>
				<h4> none </h4>
				<% else %>
				<h4><%= @user.address %></h4>
				<% end %>

				<h4 class="red-text">Phone</h4>
				<% if @user.phone == "" || @user.phone == nil %>
				<h4> none </h4>
				<% else %>
				<h4><%= @user.phone %></h4>
				<% end %>

				<h4 class="red-text">Email</h4>
				<% if @user.email == "" || @user.email == nil %>
				<h4> none </h4>
				<% else %>
				<h4><%= @user.email %></h4>
				<% end %>

				<h4 class="red-text">Likes</h4>
				<% if @user.likes == "" || @user.likes == nil %>
				<h4> none </h4>
				<% else %>
				<h4><%= @user.likes %></h4>
				<% end %>

				<h4 class="red-text">Dislikes</h4>
				<% if @user.dislikes == "" || @user.dislikes == nil %>
				<h4> none </h4>
				<% else %>
				<h4><%= @user.dislikes %></h4>
				<% end %>

				<h4 class="red-text">Additional Info</h4>
				<% if @user.add_info == "" ||  @user.add_info == nil %>
				<h4> none </h4>
				<% else %>
				<h4><%= @user.add_info %></h4>
				<% end %>
			</div>
		</div>

		<div class="col-md-2">
			<a href="/users/edit" class="btn btn-success profile-btn animated flipInX">Edit profile</a>
			<a href="/events/new" class="btn btn-success profile-btn animated flipInX">New event</a>
		</div>
	</div>


	<div class="row">
	<div class="column-wrapper-own center-block">
			<div class="col-md-6 profile-small-box-1-own">
				<h3>Upcoming events:</h3>
				<% @pending_events.each do |event| %>
				<p>
					<%= link_to event.name, event_path(event.id) %>
				</p>
				<% end %>
			</div>

			<div class="col-md-6 profile-small-box-2">
				<h3>Past events:</h3>
				<% @past_events.each do |event| %>
				<p>
					<%= link_to event.name, event_path(event.id) %>
				</p>
				<% end %>
			</div>
		</div>
	</div>
</body>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<body class="content-wrapper">
	<%= render :partial => "/layouts/navbar" %>
	
	<div class="event-box animated bounce">
		<h1><center>All Users</center></h1>

		<ul>
			<% @users.each do |user| %>
			<li> <%= link_to user.email, user_path(user) %> </li>
			<% end %>
		</ul>

	</div>
</body>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<% if current_user == @user %>
	<%= render 'own_profile' %>
<% else %>
	<%= render 'other_profile' %>
<% end %>