config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  post "events/:id/add_existing_users" => "events#add_existing_users", as: :add_existing_users
  post "events/:id/add_new_users" => "events#add_new_users", as: :add_new_users
  patch "events/:id/add_participation" => "events#add_participation", as: :add_participation
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/' => 'home#index', as: :home

  resources :users
  resources :events

end

app/models/event.rb
class Event < ActiveRecord::Base
	
	has_many :users, through: :event_users
	has_many :event_users
	has_many :exchanges

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    @title = 'All events'
  end

  def show
    @event = Event.find(params[:id])
    join = EventUser.where(event_id: @event.id, admin: true).last
    user = User.find join.user_id
    @host = user.email 
    @users = @event.users
    allUsers = User.all
    @allOptOutUsers = []

    # if a user is participating in the event
    # exclude any users from the list of system users
    # so they can't be readded to the event
    dontadd = []
    @users.each do |event_user|
      if user_participating_in_event(@event.id, event_user.id)
        dontadd << event_user
      end
    end

    # remove participating users from @allOptOutsers
    allUsers.each do |system_user|
      if !dontadd.include?(system_user)
        @allOptOutUsers << system_user
      end
    end
    #User.Mailer.gift_assigned(@event, @users).deliver_later
    @title = @event.name
  end

  def new
    @event = Event.new
    @title = 'New event'
  end

  def create
    @event = Event.new(event_params)
    @user = current_user
    if @event.save 
      #
      # User has created an event so is now designated an admin. Set 
      # the admin & participation field to 'true' on the EventUser table.
      #
      current_user.events << @event
      EventUser.last.update admin: true, participation: true
      UserMailer.new_event(@event, @user).deliver_later
      flash[:notice] = "Your event was created."
      redirect_to event_path @event
    else 
      flash[:alert] = "There was a problem creating your event."
      render "new"
    end
  end

  def edit
    @event = Event.find params[:id]
    @title = 'Edit event'
  end

  def update
    #
    # get the current event and update it with the data supplied by the user
    #
    event = Event.find params[:id]
    if event
      event.update event_params
      flash[:notice] = "Your event was modified successfully."
    else
     flash[:alert] = "There was a problem editing your event."
   end     
   redirect_to event_path params[:id]
 end

 def destroy
  @event = Event.find(params[:id])
  if @event.destroy
    flash[:notice] = "The event was deleted successfully."
    redirect_to events_path
  else
    flash[:alert] = "There was a problem deleting the event."
    redirect_to @event
  end
end

def add_existing_users
  flash[:notice] = "Users have been added to the event successfully."

  event = Event.find params[:id]
  params[:user_ids].each do |user_id|
    user = User.find user_id
    user.events << event
      # check the user's record in the EventUsers join table,
      # set the participation bit
      EventUser.last.update participation: true
    end
    redirect_to event_path params[:id]
  end

  def add_new_users
    @event = Event.find(params[:id])
    users = params[:email].gsub(/\s+/,"")
    emails = users.split(",")
    flash[:notice] = ""
    flash[:alert]=""
    #creating new users taking the emails from above
    emails.each do |email|
      @user = User.create email: email, password: "12345678"
      if @user
        @user.events << @event
        EventUser.last.update participation: true
        flash[:notice] += "Users #{email} created successfully."
        #UserMailer.welcome_email_alt(@event, @user).deliver_later
      else
       flash[:alert] += "Failed to create user #{email}."
     end 
   end
   redirect_to event_path @event
 end

private
def event_params
  params.require(:event).permit(:name, :date, :location, :deadline, :max_price, :min_price)
end

include EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  # helper_method :match_giver_to_giftee, :user_participating_in_event, :event_exchanges, :event_users, :set_EventUser_column

  # Set User user_id's participation or admin to value for 
  # Event event_id as determined by column
  def set_EventUser_column(event_id, user_id, value, column="admin")

  end

  # return a list of an event's users; participating by default,
  # but if value equals false, return non-participating
  def event_users(event_id, value=true)

  end

  # return all exchanges for an event
  # 
  def event_exchanges(event_id)
  	return Exchange.where(event_id: event_id)
  end

  # return true if user is participating in event
  # 
  def user_participating_in_event(event_id, user_id)
  	retval = false
  	event = Event.find event_id
  	join = EventUser.where(event_id: event_id, user_id: user_id).last
  	if join
  		retval = join.participation
  	end
  	return retval
  end

  def match_giver_to_giftee(event_id)

    # delete the existing exchanges for the event
    exes = Exchange.where(event_id: event_id)
    exes.each do |exch|
      exch.destroy
    end

    # get the event from the id
    event = Event.find event_id
    # get the event's participating users
    users = event.users
    join = EventUser.where(event_id: event_id)
    optin_users = []
    index = -1

    users.each do |euser|
      # check the user's record in the EventUsers join table
      if join.any?{|a| a.user_id == euser.id}
      	index = join.find_index {|item| item.user_id == euser.id}
      	if join[index].participation
      		optin_users << euser
      	end
      end
  end
    # shuffle the participating user array
    optin_users.shuffle!
    # go through the shuffled array and assign n to n+1 and
    # tail to head of the list, and add them to the event
    #
    count = optin_users.length
    if (count > 1)
    	for i in 0..count-2 do
        # puts "gifter: #{optin_users[i].email} giftee: #{optin_users[i+1].email} ---------------------------"
        event.exchanges << Exchange.new(gifter: optin_users[i].id, giftee: optin_users[i+1].id, event_id: event_id)
    end
      # puts "gifter: #{optin_users.last.email} giftee: #{optin_users[0].email} ---------------------------"
      event.exchanges << Exchange.new(gifter: optin_users.last.id, giftee: optin_users[0].id, event_id: event_id)
  else
  	flash[:alert] = "#{optin_users[0].username} is currently the only participator in this gift exchange." if count == 1
  end
end
end

app/views/events/_lb_event_create_user.html.erb
<%= form_tag add_new_users_path(@event.id) do %> 
<div class="field">
	<%= label_tag :email %><br />
	<%= text_area_tag :email %>
</div>
<div class="actions">
	<%= submit_tag "Sign up" %>
</div>
<% end %>

app/views/events/_lb_event_show_gift_pairs.html.erb
<% exes = event_exchanges(@event.id) %>	
<% exes.each do |exchange| %>	
	<p>
		<% gifter = User.find exchange.gifter %>
		<% giftee = User.find exchange.giftee %>
		<h3><%= "#{gifter.email} is giving to #{giftee.email}" %></h3>
	</p>
<% end %>

app/views/events/_other_event.html.erb
<body class="content-wrapper">

	<%= render :partial => "/layouts/navbar" %>

	<div class="profile-large-box-alt">

		<h1><center><%= @event.name %></center></h1>
		<br>
		<b>Date: </b><%= @event.date %>
		<br>
		<b>Location: </b><%= @event.location%>
		<br>
		<b>Last possible day to backout: </b><%= @event.deadline%>
		<br>
		<b>Host: </b><%= @host %>
		<br>
		<b>Maximum gift price: </b><%= @event.max_price%>
		<br>
		<b>Minimum gift price: </b><%= @event.min_price%>
		<br>
		<b>Participants:</b>
		<% @users.each do |user| %>
			<ul>
				<li><%= "#{user.username} #{user.fname} #{user.lname} #{user.email}" %></li>
			</ul>
		<% end %>
	</div>
		
</body>			

app/views/events/_own_event.html.erb
<body class="content-wrapper">

	<%= render :partial => "/layouts/navbar" %>

	<div class="row profile-row">

		<div class="col-md-10">
			<div class="profile-large-box">

				<h1><center><%= @event.name %></center></h1>
				<br>
				<b>Date: </b><%= @event.date %>
				<br>
				<b>Location: </b><%= @event.location%>
				<br>
				<b>Last possible day to backout: </b><%= @event.deadline%>
				<br>
				<b>Host: </b><%= @host %>
				<br>
				<b>Maximum gift price: </b><%= @event.max_price%>
				<br>
				<b>Minimum gift price: </b><%= @event.min_price%>
				<br>
				<b>Participants:</b>
				<% @users.each do |user| %>
				<ul>
					<li><%= "#{user.username} #{user.fname} #{user.lname} #{user.email}" %></li>
				</ul>
				<% end %>
			</div>
		</div>

		<div class="col-md-2">
			<p><%= link_to "Edit this event", edit_event_path(@event.id), class: "btn btn-success event-btn animated flipInX" %></p>
			<p><%= link_to "Add a User to this event", "#event_add_users_lb", class: "btn btn-success event-btn animated flipInX fancybox" %></p>
			<p><%= link_to "Create a User for this event", "#event_create_users_lb", class: "btn btn-success event-btn animated flipInX fancybox" %></p>
			<p><%= link_to "Secret Santize This Event", "#event_santize_lb", class: "btn btn-success event-btn animated flipInX fancybox" %></p>			
		</div>
	</div>


	<!-- lightbox for adding existing system users -->
	<div style="display:none;">
		<div id="event_add_users_lb">
			<p>
				<%= form_tag add_existing_users_path(@event.id) do %> 
				<table id="addUsersTable" class="display">
					<thead>
						<tr>
							<th><%= submit_tag "Add" %></th>
							<th>Username</th>
							<th>First Name</th>
							<th>Last Name</th>
						</tr>
					</thead>
					<tbody>
						<% @allOptOutUsers.each do |user| %>
							<tr>
								<td><%= check_box_tag "user_ids[]", user.id %></td>
								<td><%= user.username %></td>
								<td><%= user.fname %></td>
								<td><%= user.lname %></td>
							</tr>
						<% end %>
					</tbody>
				</table>  
				<% end %>
			</p>
		</div>
	</div>
	<!-- lightbox for creating system users for the event -->
	<div style="display:none;">
		<div id="event_create_users_lb">
			<p>
			Add an email for each user you would like to create, separated by commas.
				<%= render 'lb_event_create_user' %>
			</p>
		</div>
	</div>

	<!-- lightbox for creating system users for the event -->
	<div style="display:none;">
		<div id="event_santize_lb">
			<p>
				Below are the gift assignments pertaining to this event.
				<% match_giver_to_giftee @event.id %>
				<%= render 'lb_event_show_gift_pairs' %>	
			</p>
		</div>
	</div>
	</body>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<body class="content-wrapper">

	<%= render :partial => "/layouts/navbar" %>

	<div class="bigger-form-box animated bounce">
		<h1>Edit Event</h1>

		<% if @event.errors.full_messages.any?%>
		<ul>
			<% @event.errors.full_messages.each do |error_message| %>
			<li> <%= error_message %> </li> <br>
			<% end %>
		</ul>
		<% end %>

		<%= form_for @event, url: @event do |f| %>
		<%= f.label :name, 'Name:' %>
		<%= f.text_field :name %>
		<br><br>
		<%= f.label :date, 'Date:' %>
		<%= f.datetime_select :date %>
		<br><br>
		<%= f.label :location, 'Location:' %>
		<%= f.text_field :location %>
		<br><br>
		<%= f.label :deadline, 'Participation deadline:' %>
		<%= f.datetime_select :deadline %>
		<br><br>
		<%= f.label :max_price, 'Maximum gift price:' %>
		<%= f.text_field :max_price %>
		<br><br>
		<%= f.label :min_price, 'Minimum gift price:' %>
		<%= f.text_field :min_price %>
		<br><br>
		<%= f.submit :'change event' %>
		<% end %>
	</div>

	<div class="bigger-form-box animated bounce">

	  <h3>Delete this event</h3>

	  <p>Unhappy? <%= button_to "Delete", event_path(@event), method: :delete %></p>
	</div>

	<div class="bigger-form-box animated bounce">
		<%= link_to "Back", :back %>
	</div>
</body>			

app/views/events/index.html.erb
<body class="content-wrapper">

	<%= render :partial => "/layouts/navbar" %>
	
	<div class="event-box animated bounce">
		<h1><center>All Events</center></h1>

		<ul>
			<% @events.each do |event| %>
			<% join = EventUser.where(event_id: event.id, admin: true).last %>
			<% user = User.where(id: join.user_id).last %>
			<% @host = user.email %>
			<li> <%= link_to event.name, event_path(event) %> hosted by <%= link_to @host, user_path(user) %> </li>
			<% end %>
		</ul>

	</div>
</body>

app/views/events/new.html.erb
<body class="content-wrapper">

	<%= render :partial => "/layouts/navbar" %>
	
	<div class="bigger-form-box animated bounce">
		<% if @event.errors.full_messages.any?%>
		<ul>
			<% @event.errors.full_messages.each do |error_message| %>
			<li> <%= error_message %> </li> <br>
			<% end %>
		</ul>
		<% end %>

		<h2>New Event</h2>
		<%= form_for @event, url: @event do |f| %>
		<%= f.label :name, 'Name:' %>
		<%= f.text_field :name %>
		<br><br>
		<%= f.label :date, 'Date:' %>
		<%= f.datetime_select :date %>
		<br><br>
		<%= f.label :location, 'Location:' %>
		<%= f.text_field :location %>
		<br><br>
		<%= f.label :deadline, 'Participation deadline:' %>
		<%= f.datetime_select :deadline %>
		<br><br>
		<%= f.label :max_price, 'Maximum gift price:' %>
		<%= f.text_field :max_price %>
		<br><br>
		<%= f.label :min_price, 'Minimum gift price:' %>
		<%= f.text_field :min_price %>
		<br><br>
		<%= f.submit :'Add event' %>
		<% end %>
	</div>	
	
	<div class="bigger-form-box animated bounce">
		<%= link_to "Back", :back %>
	</div>
</body>		

app/views/events/show.html.erb
<% if current_user.email == @host %>
	<%= render 'own_event' %>
<% else %>
	<%= render 'other_event' %>
<% end %>